name: Cypress A11y Tests

on:
    workflow_dispatch:

jobs:
    test-a11y:
        timeout-minutes: 30
        runs-on: ubuntu-latest

        env:
            TERM: xterm-256color

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x

            - name: Install dependencies
              run: npm ci

            - name: Run Cypress A11y tests
              run: npm run test:a11y

            - name: Generate Axe HTML Reports
              if: always()
              run: |
                  if [ -d "axe-reports" ]; then
                    echo "Axe reports found."
                  else
                    echo "No axe reports generated."
                  fi

            - name: Combine and Generate Mochawesome
              if: always()
              run: |
                  npm run combine-reports
                  npm run generate-report

            - name: Upload Accessibility HTML Reports
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: axe-accessibility-reports
                  path: axe-reports/
                  retention-days: 14

            - name: Upload Mochawesome Report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: mochawesome-a11y-report
                  path: cypress/reports/mochareports/report.html
                  retention-days: 14

            - name: Publish CTRF Test Report
              uses: ctrf-io/github-test-reporter@v1
              with:
                  report-path: "./ctrf/*.json"
                  github-report: true
              if: always()
