name: Cypress Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests with CTRF + Mochawesome reporters
        run: |
          npx cypress run \
            --reporter mochawesome \
            --reporter-options reportDir=cypress/reports/mochawesome,overwrite=false,html=false,json=true \
            --reporter ctrf-mocha-reporter \
            --reporter-options outputDir=cypress/reports/ctf

      - name: Check if CTRF JSON exists
        run: |
          if ls cypress/reports/ctf/*.json 1> /dev/null 2>&1; then
            echo "CTRF reports found";
          else
            echo "No CTRF reports found!";
            exit 1;
          fi

      - name: Publish CTRF report (GitHub Test Reporter)
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: "cypress/reports/ctf/*.json"
          github-report: true
        if: always()

      - name: Combine Mochawesome JSON files
        run: npx mochawesome-merge cypress/reports/mochawesome/*.json > cypress/reports/mochawesome/mochawesome.json

      - name: Generate Mochawesome HTML report
        run: npx marge cypress/reports/mochawesome/mochawesome.json --reportDir cypress/reports/mochareports

      - name: Upload Mochawesome HTML report to GitHub Actions
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/mochareports
          retention-days: 14
